refactor: switched dependencies status badge
JS-DevTools/npm-publish pull request #50
Opened 2022-04-10 10:06 UTC by mfranzke

Closes #49

Switched to https://requires.io/ service – you would need to register previous to being able to use this badge.

2022-05-13 15:19 UTC, philsturgeon commented
Thanks for this, but the new one also seems to not work unfortunately?

2022-05-13 16:16 UTC, mfranzke commented
> Thanks for this, but the new one also seems to not work unfortunately?

You would need to register at that service first (which I obviously didn‘t want to do intead of you); it works quite nice, at least see one of my repositories badges:
https://requires.io/github/mfranzke/loading-attribute-polyfill/requirements.svg?branch=main

2023-04-07 15:52 UTC, mcous requested changes
Unfortunately, requires.io appears to have shut down. Could you remove the badge, instead?

2023-04-07 18:10 UTC, mcous approved these changes

2023-04-07 18:11 UTC, merged