Use registry configured in options
JS-DevTools/npm-publish pull request #56
Opened 2022-07-15 05:31 UTC by honzabilek4

2022-07-15 05:32 UTC, honzabilek4 commented
Closes #55

2023-04-07 15:30 UTC, mcous requested changes

2023-04-07 15:30 UTC, mcous commented on src/npm.ts
> +      if(options.registry){
Please match code style! In the mean time, I'll work on getting `prettier` integrated

```suggestion
      if (options.registry) {
```

2023-04-07 15:32 UTC, mcous commented
My mistake, upon further investigation, I think this is working correctly based on previous discussion in #55, so I'm going to close this PR. Let me know if you disagree and I'll dig in a little further

2023-04-07 15:32 UTC, closed without merging